FROM mcr.microsoft.com/playwright/python:v1.49.0-noble

WORKDIR /tests

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENTRYPOINT ["python", "-m", "pytest", "-v"]
